name: package_reports
description: Package de criação de relatórios, gráficos e exportação para excel, tudo automaticamente a partir de uma entrada de JSON.
version: 1.0.0
#publish_to: none
repository: https://github.com/jacsontiede85/package_reports
homepage: https://github.com/jacsontiede85/package_reports

platforms:
  android:
  ios:
  web:
  windows:
  linux:

licenses:
  - "MIT"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.19.0
  mobx: ^2.3.3
  flutter_mobx: ^2.2.1+1
  http: ^1.2.1
  crypto: ^3.0.3
  loading_animation_widget: ^1.2.1
  adaptive_scrollbar: ^2.1.2
  universal_html: ^2.2.4
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  syncfusion_flutter_charts: ^27.1.56
  syncfusion_flutter_xlsio: ^27.1.56
  responsive_builder: ^0.7.1
  shared_preferences: ^2.3.2
  pdf: ^3.11.1
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
