name: package_reports
description: Package de criação de relatórios, gráficos e exportação para excel, tudo automaticamente a partir de uma entrada de JSON.
version: 0.0.3
#publish_to: none
repository: https://github.com/jacsontiede85/package_reports
homepage: https://github.com/jacsontiede85/package_reports

platforms:
  android:
  ios:
  web:
  windows:
  linux:

licenses:
  - "MIT"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  get_it: ^7.6.7
  http: ^1.2.1
  crypto: ^3.0.3
  loading_animation_widget: ^1.2.0+4
  adaptive_scrollbar: ^2.1.2
  universal_html: ^2.2.4
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.2.6
  syncfusion_flutter_xlsio: ^24.2.6
  syncfusion_flutter_core: ^24.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true
